baseUrl = "https://mhay10.github.io"
title = "Maxwell Hay"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "docs"

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Maxwell Hay"
info = "Look around my projects and posts about programming<br>and other things I find interesting"
description = "Maxwell Hay's website"
keywords = ["blog", "programming", "personal"]
avatarurl = "avatar.png"

favicon_32 = "favicon.png"
favicon_16 = "favicon.png"

colorScheme = "auto"
hideColorSchemeToggle = false

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/mhay10/"

# Menu links
[[menu.main]]
name = "Projects"
url = "projects/"
weight = 1

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 2
